#!/bin/bash
# setup-n8n.sh - Configura n8n con el workflow de CV Evaluator
# Este script se ejecuta desde el host de Coolify

echo "=========================================="
echo "  n8n Setup - CV Evaluator Integration"
echo "=========================================="
echo ""

# n8n esta accesible internamente via el alias de red
# Pero necesitamos exponerlo temporalmente para obtener la API key

echo "Para configurar n8n necesitas:"
echo ""
echo "1. Exponer n8n temporalmente en Coolify:"
echo "   - Ve a tu panel de Coolify"
echo "   - Abre el servicio N8N"
echo "   - Agrega un FQDN publico temporal (ej: n8n.automate-n8n.online)"
echo "   - Guarda y espera a que el deploy termine"
echo ""
echo "2. Abre n8n en tu navegador y genera una API Key:"
echo "   - Settings (icono de engranaje) > API > Generate API Key"
echo "   - Copia la API Key"
echo ""
echo "3. Configura las credenciales de Gmail en n8n:"
echo "   - Credentials > Add Credential > Gmail OAuth2"
echo "   - Necesitas crear OAuth credentials en Google Cloud Console:"
echo "     a. Ve a https://console.cloud.google.com/"
echo "     b. Crea un proyecto o selecciona uno existente"
echo "     c. APIs & Services > Credentials > Create Credentials > OAuth client ID"
echo "     d. Application type: Desktop app (o Web application)"
echo "     e. Descarga el JSON de credenciales"
echo "   - En n8n, completa el flujo OAuth haciendo clic en 'Sign in with Google'"
echo ""
echo "4. Una vez tengas la API Key de n8n, ejecuta:"
echo ""
echo "   export N8N_API_KEY=tu-api-key-aqui"
echo "   export N8N_URL=https://n8n.automate-n8n.online"
echo "   python3 n8n/n8n_setup.py --check"
echo ""
echo "5. Cuando el check pase, crea el workflow manualmente:"
echo "   - En n8n, clic en 'Add workflow'"
echo "   - Agrega un nodo 'Gmail Trigger'"
echo "     * Poll Times: Every minute"
echo "     * Trigger On: message"  
echo "     * Options: Download Attachments = true"
echo "     * Credential: tu credencial de Gmail OAuth2"
echo ""
echo "   - Agrega un nodo 'Filter'"
echo "     * Condition: Subject contiene 'cv' OR 'curriculum' OR 'hoja de vida' OR 'resume'"
echo ""
echo "   - Agrega un nodo 'Split Out' (para separar adjuntos)"
echo "     * Field to Split Out: attachments"
echo ""
echo "   - Agrega un nodo 'HTTP Request'"
echo "     * Method: POST"
echo "     * URL: http://cv-evaluator:8000/api/candidates/upload"
echo "     * Authentication: Header Auth"
echo "       - Name: X-API-Key"
echo "       - Value: cv-eval-k3y-s3cur3-2026-automate"
echo "     * Body: multipart/form-data"
echo "       - file: (binary data del attachment)"
echo "     * Query Parameters:"
echo "       - email: {{ $json.headers.from }}"
echo ""
echo "   - Conecta los nodos: Gmail -> Filter -> Split Out -> HTTP Request"
echo "   - Activa el workflow"
echo ""
echo "=========================================="
echo "  O ALTERNATIVA MAS SIMPLE"
echo "=========================================="
echo ""
echo "Puedes importar el workflow JSON directamente:"
echo "1. En n8n, clic en los 3 puntos (menu) > Import from File"
echo "2. Selecciona: n8n/cv-evaluator-workflow.json"
echo "3. Actualiza la credencial de Gmail en el nodo Gmail Trigger"
echo "4. Actualiza la URL y API key en el nodo HTTP Request"
echo "5. Activa el workflow"
echo ""